### ISSUE TITLE
Problems with root import 

### ISSUE THREAD

**Issue by joelpiccoli** [entwicklerstube/babel-plugin-root-import#109]
Hello everyone!
I'm trying to solve that nasty problem of the infinite '../../../' from our imports using the babel-plugin-root-import, but I'm having problem with make it work properly, I'm using it in React Native btw.

I followed the steps and configs as it should be, but I can't make it work! What am I doing wrong?

**This is my .babelrc**
```
{
  "presets": [
    "react-native",
    "react-native-dotenv",
    "babel-preset-react-native-stage-0/decorator-support",
    "babel-plugin-root-import"
  ],
  "plugins": [
    ["babel-plugin-root-import", {
      "paths": [{
        "rootPathSuffix": "src",
        "rootPathPrefix": "~"
      }]
    }]
  ],
  "env": {
    "development": {
      "plugins": [
        "transform-react-jsx-source",
        ["babel-plugin-root-import", {
          "paths": [{
            "rootPathSuffix": "src",
            "rootPathPrefix": "~"
          }]
        }]
      ]
    }
  }
}
```

**Here is the import I'm trying to do**
```
import LoginScreen from '~/components/pages/auth/LoginScreen';
```

And here is the error I get on the emulator (Android):

```
The development server returned response error code: 500

URL: http://10.0.2.2:8081/index.delta?platform=android&dev=true&minify=false

Body:
{"originModulePath":"/home/joelpiccoli/workspace/beefapp/src/routes/stacks/AuthStack.js","targetModuleName":"./src/components/pages/auth/LoginScreen","message":"Unable to resolve module `./src/components/pages/auth/LoginScreen` from `/home/joelpiccoli/workspace/beefapp/src/routes/stacks/AuthStack.js`: The module `./src/components/pages/auth/LoginScreen` could not be found from `/home/joelpiccoli/workspace/beefapp/src/routes/stacks/AuthStack.js`. Indeed, none of these files exist:\n\n  * `/home/joelpiccoli/workspace/beefapp/src/routes/stacks/src/components/pages/auth/LoginScreen(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`\n  * `/home/joelpiccoli/workspace/beefapp/src/routes/stacks/src/components/pages/auth/LoginScreen/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`","errors":[{"description":"Unable to resolve module `./src/components/pages/auth/LoginScreen` from `/home/joelpiccoli/workspace/beefapp/src/routes/stacks/AuthStack.js`: The module `./src/components/pages/auth/LoginScreen` could not be found from `/home/joelpiccoli/workspace/beefapp/src/routes/stacks/AuthStack.js`. Indeed, none of these files exist:\n\n  * `/home/joelpiccoli/workspace/beefapp/src/routes/stacks/src/components/pages/auth/LoginScreen(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`\n  * `/home/joelpiccoli/workspace/beefapp/src/routes/stacks/src/components/pages/auth/LoginScreen/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`"}],"name":"Error","stack":"Error: Unable to resolve module `./src/components/pages/auth/LoginScreen` from `/home/joelpiccoli/workspace/beefapp/src/routes/stacks/AuthStack.js`: The module `./src/components/pages/auth/LoginScreen` could not be found from `/home/joelpiccoli/workspace/beefapp/src/routes/stacks/AuthStack.js`. Indeed, none of these files exist:\n\n  * `/home/joelpiccoli/workspace/beefapp/src/routes/stacks/src/components/pages/auth/LoginScreen(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`\n  * `/home/joelpiccoli/workspace/beefapp/src/routes/stacks/src/components/pages/auth/LoginScreen/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`\n    at ModuleResolver.resolveDependency (/home/joelpiccoli/workspace/beefapp/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:161:851)\n    at ResolutionRequest.resolveDependency (/home/joelpiccoli/workspace/beefapp/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:91:16)\n    at DependencyGraph.resolveDependency (/home/joelpiccoli/workspace/beefapp/node_modules/metro/src/node-haste/DependencyGraph.js:272:4579)\n    at dependencies.map.relativePath (/home/joelpiccoli/workspace/beefapp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:376:19)\n    at Array.map (<anonymous>)\n    at resolveDependencies (/home/joelpiccoli/workspace/beefapp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:374:16)\n    at /home/joelpiccoli/workspace/beefapp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:212:33\n    at Generator.next (<anonymous>)\n    at step (/home/joelpiccoli/workspace/beefapp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:297:313)\n    at /home/joelpiccoli/workspace/beefapp/node_modules/metro/src/DeltaBundler/traverseDependencies.js:297:473"}
processBundleResult
    BundleDownloader.java:266
access$200
    BundleDownloader.java:35
onResponse
    BundleDownloader.java:153
execute
    RealCall.java:135
run
    NamedRunnable.java:32
runWorker
    ThreadPoolExecutor.java:1133
run
    ThreadPoolExecutor.java:607
run
    Thread.java:761

```

**Comment by joelpiccoli** [comment]
thanks for your help @brigand, but even in production, I keep having errors... :/

**Comment by brigand** [comment]
@joelpiccoli if you figured it out, please share for anyone that stumbles upon this issue.

**Comment by joshuapinter** [comment]
We switched to using `babel-plugin-module-resolve` instead. 

I have it working just fine on React Native 0.56.1:

### `package.json`

```json
"devDependencies": {
  "babel-plugin-module-resolver": "3.2.0"
}
```

### `.babelrc`

```
{
  "plugins": [
    [ "module-resolver", { "root": ["./src"] } ]
  ]
}
```

### `index.android.js`

```js
import Constants from "Constants";
```
