### ISSUE TITLE
React Native App MacOS process.cwd() got path in node_modules.

### ISSUE THREAD

**Issue by hy512** [entwicklerstube/babel-plugin-root-import#111]
![y4qw1rbg yk kw1 143hd4](https://user-images.githubusercontent.com/33169463/45074949-fd7d1f80-b117-11e8-80d8-260e20b42a95.png)
the below window is appendFile's content.

error detail 

```
error: bundling failed: Error: Unable to resolve module `./src/app/dao/ConfigurationWithRedux` from `/Users/provoke/Desktop/mobile/app/src/app/conf/configureStore.js`: The module `./src/app/dao/ConfigurationWithRedux` could not be found from `/Users/provoke/Desktop/mobile/app/src/app/conf/configureStore.js`. Indeed, none of these files exist:

  * `/Users/provoke/Desktop/mobile/app/src/app/conf/src/app/dao/ConfigurationWithRedux(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
  * `/Users/provoke/Desktop/mobile/app/src/app/conf/src/app/dao/ConfigurationWithRedux/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
    at ModuleResolver.resolveDependency (/Users/provoke/Desktop/mobile/app/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:158:865)
    at ResolutionRequest.resolveDependency (/Users/provoke/Desktop/mobile/app/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:92:16)
    at DependencyGraph.resolveDependency (/Users/provoke/Desktop/mobile/app/node_modules/metro/src/node-haste/DependencyGraph.js:271:4465)
    at dependencies.map.relativePath (/Users/provoke/Desktop/mobile/app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:379:19)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/provoke/Desktop/mobile/app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:378:16)
    at /Users/provoke/Desktop/mobile/app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:203:33
    at Generator.next (<anonymous>)
    at step (/Users/provoke/Desktop/mobile/app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:296:307)
    at /Users/provoke/Desktop/mobile/app/node_modules/metro/src/DeltaBundler/traverseDependencies.js:296:467
```

but in windows and linux not which.

**Comment by brigand** [comment]
Hello.

Please include your babel config, and if this is the development or production build.

Could you clarify what you mean by "but in windows and linux not which"?

**Comment by hy512** [comment]
Sorry, I mean my project doesn't have this error on windows and linux, , just on macos.

my .babelrc :
{
  "presets": [
    "react",
    "react-native"
  ],
  "plugins": [
    [
      "babel-plugin-root-import",
      {
        "rootPathSuffix": "src/app"
      }
    ],
    "transform-decorators-legacy"
  ],
  "env": {
    "production": {
      "plugins": [
        [
          "babel-plugin-root-import",
          {
            "rootPathSuffix": "src/app"
          }
        ]
      ]
    }
  }
}

And package.json :
![pzapsp 4ma0q lho7gf87](https://user-images.githubusercontent.com/33169463/45261376-185ed500-b433-11e8-926a-03613099b0b0.png)

This error occurred when starting the project through the XCode run operation, and I tried npm start also this error.

**Comment by brigand** [comment]
Try specifying it just once

```json
{
  "presets": [
    "react",
    "react-native"
  ],
  "plugins": [
    "transform-decorators-legacy"
  ],
  "env": {
    "production": {
      "plugins": [
        [
          "babel-plugin-root-import",
          {
            "rootPathSuffix": "src/app"
          }
        ]
      ]
    }
  }
}
```

The readme isn't very clear about this, sorry.
