### ISSUE TITLE
Incompatible with babel 7

### ISSUE THREAD

**Issue by vihanb** [entwicklerstube/babel-plugin-root-import#92]
Babel 7 drops support for arrays as the root value for a plugin's options. This means when using babel 7+ multiple aliases cannot be used

**Comment by billnbell** [comment]
Here is 

{
"plugins": [
    [
      "babel-plugin-root-import",
      [{
        "rootPathPrefix": "~",
        "rootPathSuffix": "core/components"
      },
      {
        "rootPathPrefix": "^",
        "rootPathSuffix": "core/styles"
      },
      {
        "rootPathPrefix": "@",
        "rootPathSuffix": "core"
      },
      {
        "rootPathPrefix": "$",
        "rootPathSuffix": "./"
      }]
    ]
  ]
}


It errors with

Error: .plugins[0][1] must be an object, false, or undefined
    at assertPluginItem (/Users/billbell/v/cf-v2/next-admin/node_modules/next/node_modules/@babel/core/lib/config/validation/option-assertions.js:157:15)
    at /Users/billbell/v/cf-v2/next-admin/node_modules/next/node_modules/@babel/core/lib/config/validation/option-assertions.js:134:14
    at Array.forEach (<anonymous>)
    at assertPluginList (/Users/billbell/v/cf-v2/next-admin/node_modules/next/node_modules/@babel/core/lib/config/validation/option-assertions.js:133:9)
    at /Users/billbell/v/cf-v2/next-admin/node_modules/next/node_modules/@babel/core/lib/config/validation/options.js:84:20
    at Array.forEach (<anonymous>)
    at validate (/Users/billbell/v/cf-v2/next-admin/node_modules/next/node_modules/@babel/core/lib/config/validation/options.js:62:21)
    at /Users/billbell/v/cf-v2/next-admin/node_modules/next/node_modules/@babel/core/lib/config/config-chain.js:141:36
    at cachedFunction (/Users/billbell/v/cf-v2/next-admin/node_modules/next/node_modules/@babel/core/lib/config/caching.js:40:17)
    at init (/Users/billbell/v/cf-v2/next-admin/node_modules/next/node_modules/@babel/core/lib/config/config-chain.js:122:12)
    at /Users/billbell/v/cf-v2/next-admin/node_modules/next/node_modules/@babel/core/lib/config/config-chain.js:206:17
    at buildRootChain (/Users/billbell/v/cf-v2/next-admin/node_modules/next/node_modules/@babel/core/lib/config/config-chain.js:85:20)
    at loadPrivatePartialConfig (/Users/billbell/v/cf-v2/next-admin/node_modules/next/node_modules/@babel/core/lib/config/partial.js:41:53)
    at loadPartialConfig (/Users/billbell/v/cf-v2/next-admin/node_modules/next/node_modules/@babel/core/lib/config/partial.js:66:16)
    at babelConfig (/Users/billbell/v/cf-v2/next-admin/node_modules/next/dist/server/build/webpack.js:88:57)
    at _callee2$ (/Users/billbell/v/cf-v2/next-admin/node_modules/next/dist/server/build/webpack.js:164:34)
mac

**Comment by billnbell** [comment]
Let's get this committed.
